name: CI
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Depoly Wiki
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
      - uses: actions/checkout@v2
      - name: Set Custom Domain
      - run: |
          mkdir CNAME_rx
          cd CNAME_rx
          echo 'wiki.calinix.tech' > CNAME
          cat CNAME

